#!/usr/local/bin/php
<?php


$udata = ['name'=>'не указано','email'=>'не указано','password'=>'не указано'];
//function input(&$udata, $text, $field){}
//input($udata, "name", "");



print("Необходимо зарегистрироватся для использования сервиса. \nВаше имя: ");
$stdin = fopen("php://stdin", "r");
$udata['name'] = trim(fgets($stdin));
fclose($stdin);

print("Ваш email: ");
$stdin = fopen("php://stdin", "r");
$udata['email'] = trim(fgets($stdin));
fclose($stdin);

print("Теперь пароль: ");
goto repassStep; repass:
print("Оопа-па пароли не совпадают! Введите новый пароль еще раз \n Пароль: ");
repassStep:

$stdin = fopen("php://stdin", "r");
$udata['password'] = trim(fgets($stdin));
fclose($stdin);

print("Повторите пароль: ");
$stdin = fopen("php://stdin", "r");
if(trim(fgets($stdin)) !== $udata['password']) goto repass;
fclose($stdin);

print("\nВсе верно?:");
print("\n - Имя: ".$udata['name']);
print("\n - Возраст: ".$udata['email']);
print("\n - Пароль: ".$udata['password']);

print("\nЕсли все верно, ");

confirm:

print("ведите Yes, или No для отметы, и нажмите Enter: ");
$stdin = fopen("php://stdin", "r");
$confirm = trim(fgets($stdin));
fclose($stdin);

switch (strtolower($confirm)) {
    case 'yas':
    case 'y':
    case 'да':
    case 'д':
        print("Вы успешно зарегестрированы.\n");
        break;

    case 'no':
    case 'n':
    case 'нет':
    case 'н':
        print("Вы отказались от зарегестрации.\n");
        break;
    
    default:
        print("Не верный ключ, ");
        goto confirm;
        break;
}

?>