#!/usr/local/bin/php
<?php
/**
 * Example: "php sapi command opt1 opt2 opt3 opt4"
 * $argc - 6 (args num)
 * $argv - [sapi, command, op...] array input words
 */


class Sapi {

  private $argv = [];
  private $program = null;

  private $programFile = null;
  private $programName = null;
  private $command = null;
  private $options = [];

  public $config = [
    'version' => '0.0.1',
    'programs_dir' => __DIR__.'/sapilib/programs/'
  ];

  public function __construct($argv){
    $this->argv = $argv;
    array_shift($argv);

    $this->programName = trim(array_shift($argv));
    $this->command = trim(array_shift($argv));
    $this->options = $argv;

    if($this->programName == '--help' || $this->programName == '-h'){
      print(">> Вызвана помощь 'SAPI'. \n");
      print("Синтаксис кооманд 'php sapi program [opt1 [opt2 [opt3] ] ]'\n");
      print("  'program' - название скрипта программы\n");
      print("  'opt1 ...' - опции переданые программе 'program'\n");
      print("Для помощи конктретной программы наберите 'php sapi program --help' или '-h'\n");
      exit(">> Программа завершена. Всего доброго.\n");
    }

    if($this->programName == '--list' || $this->programName == '-l'){      
      system('ls -la '.$this->config['programs_dir']);
      exit(">> Программа завершена. Всего доброго.\n");
    }

    $this->callProgram($this->programName);
  }

  public function callProgram($program){
    $this->programFile = $this->config['programs_dir'].$this->programName.'.php';
    if(is_file($this->programFile)){
      require_once ($this->programFile);
      $this->program = new $this->programName($this, $this->command, $this->options);
    }
  }

  public function __get($name){
    switch (trim($name)) {
      case 'name':
        return $this->programName;
        break;
        
      case 'program':
        return $this->program;
        break;
        
      case 'command':
        return $this->command;
        break;
        
      case 'options':
        return $this->options;
        break;
      
      default: break;
    }
  }
  
  static public function input($sendData, $callback){
    print($sendData);
    $stdin = fopen("php://stdin", "r");
    $response = trim(fgets($stdin));
    fclose($stdin);
    if(is_callable($callback))
      $callback($response);
  }


  static public function message($send, $nl = true){
    if(is_array($send)){
      foreach ($send as $key => $value) {
        if(is_string($key)) $key = "  '" .$key. "' - ";
        else $key = "";
        print($key. $value . ($nl?"\n":""));
      }
    }else
      print("" .$send. ($nl?"\n":""));
  }

  static public function confirm($message, $callback, $fake = false){
    $message = $message ? $message : "Confirm Yes/No: ";
    self::input($message, function($response) use ($message, $callback, $fake) {
      if($fake) $response = 'yes';
      switch (strtolower(trim($response))) {
        case 'yes': case 'y': 
          $callback(true); 
          break;
        case 'no': case 'n': 
          $callback(false); 
          break;
        default: 
          print("Try again. "); 
          self::confirm($message, $callback);
        break;
      }
    });
  }

}

$sapi = new Sapi($argv);

?>
